### ISSUE TITLE
An easier way to add movies

### ISSUE THREAD

**Issue by 0xsmoos** [LikeToAccess/PMD#2]
The idea is that all the user has to do is type into discord what movie/tv shows they want, and get back search results for what they typed in.

> The backend could be done with Selenium
> The frontend could be done through the bot using embeds
> The user would pick from the search results by  reacting on the message with which movie they want

[Edited by LikeToAccess]

**Comment by LikeToAccess** [comment]
This issue you mentioned with having to use inspect element has been fixed, although it's still not as simple as typing in the name of the movie you want. The current version works without a VPN and without Inspect Element. All you need to do is grab the link to the movie from the address bat at the top.

**Comment by 0xsmoos** [comment]
> This issue you mentioned with having to use inspect element has been fixed, although it's still not as simple as typing in the name of the movie you want. The current version works without a VPN and without Inspect Element. All you need to do is grab the link to the movie from the address bat at the top.

This is a good start. Hopefully we can implement this relatively soon. I think the easier it is to add movies, there will be more engagement, which is valuable.
